<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ProjectTypeGuids>{3AC096D0-A1C2-E12C-1390-A8335801FDAB};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>
    <TestProjectType>UnitTest</TestProjectType>
    <AssemblyName>Confluent.Kafka.UnitTests</AssemblyName>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Confluent.Kafka.UnitTests.snk</AssemblyOriginatorKeyFile>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Confluent.Kafka/Confluent.Kafka.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <!-- Needed for testing net462 on Linux -->
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="18.9.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

</Project>
