// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Confluent.Kafka.Examples.AvroSpecific
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class User : ISpecificRecord
	{
		// properties could be simplified and innitializations be shortened
		public virtual Schema Schema => Avro.Schema.Parse(@"{""type"":""record"",""name"":""User"",""namespace"":""confluent.io.examples.serialization.avro"",""fields"":[{""name"":""name"",""type"":""string""},{""name"":""favorite_number"",""type"":""long""},{""name"":""favorite_color"",""type"":""string""},{""name"":""hourly_rate"",""default"":null,""type"":[""null"",{""type"":""bytes"",""logicalType"":""decimal"",""precision"":4,""scale"":2}]}]}");
		private string _name;
		private long _favorite_number;
		private string _favorite_color;
		private System.Nullable<Avro.AvroDecimal> _hourly_rate;
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public long favorite_number
		{
			get
			{
				return this._favorite_number;
			}
			set
			{
				this._favorite_number = value;
			}
		}
		public string favorite_color
		{
			get
			{
				return this._favorite_color;
			}
			set
			{
				this._favorite_color = value;
			}
		}
		public System.Nullable<Avro.AvroDecimal> hourly_rate
		{
			get
			{
				return this._hourly_rate;
			}
			set
			{
				this._hourly_rate = value;
			}
		}
		public virtual object Get(int fieldPos) => fieldPos switch
		{
			0 => name,
			1 => favorite_number,
			2 => favorite_color,
			3 => hourly_rate,
			_ => throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()")
		};
		public virtual void Put(int fieldPos, object fieldValue)
		{
			object example = fieldPos switch
			{
				0 => name = (string)fieldValue,
				1 => favorite_number = (Int64)fieldValue,
				2 => favorite_color = (string)fieldValue,
				3 => hourly_rate = (System.Nullable<Avro.AvroDecimal>)fieldValue,
				_ => throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()")
			};
		}
	}
}
