namespace Confluent.Kafka
{
    public struct GroupMemberInfo {

        public GroupMemberInfo(string memberId, string clientId, string clientHost, byte[] memberMetadata, byte[] memberAssignment)
        {
            MemberId = memberId;
            ClientId = clientId;
            ClientHost = clientHost;
            MemberMetadata = memberMetadata;
            MemberAssignment = memberAssignment;
        }

        public string MemberId { get; }            /**< Member id (generated by broker) */
        public string ClientId { get; }            /**< Client's \p client.id */
        public string ClientHost { get; }          /**< Client's hostname */

        // TODO: Think about what the object model might look like if we were to ever
        //       add functionality to interpret this byte[] data. Is the below API what
        //       we want? (probably I think)
        public byte[] MemberMetadata { get; }      /**< Member metadata (binary),
                                                         *   format depends on \p protocol_type. */
        public byte[] MemberAssignment { get; }    /**< Member assignment (binary),
                                                         *   format depends on \p protocol_type. */
    }
}
