namespace Confluent.Kafka
{
    public struct GroupMemberInfo {
        public string MemberId { get; set; }            /**< Member id (generated by broker) */
        public string ClientId { get; set; }            /**< Client's \p client.id */
        public string ClientHost { get; set; }          /**< Client's hostname */
        public byte[] MemberMetadata { get; set; }      /**< Member metadata (binary),
                                                         *   format depends on \p protocol_type. */
        public byte[] MemberAssignment { get; set; }    /**< Member assignment (binary),
                                                         *   format depends on \p protocol_type. */
    }
}
