using AvroSpecificWebApi.Entities;
using Confluent.Kafka;
using Confluent.SchemaRegistry;
using Confluent.SchemaRegistry.Serdes;
using System.Collections.Generic;

namespace AvroSpecificWebApi
{
    public class ProducerFactory
    {
        private static object _syncObject = new object();
        private static Dictionary<Entities.ProducerSettings, IProducer<string, User>> _producers = new Dictionary<ProducerSettings, IProducer<string, User>>();
        
        public IProducer<string, User> GetProducer(Entities.ProducerSettings producerSettings)
        {
            IProducer<string, User> returnValue;

            if (_producers.TryGetValue(producerSettings, out returnValue) == false)
            {
                lock (_syncObject)
                {
                    if (_producers.TryGetValue(producerSettings, out returnValue) == false)
                    {
                        var producerConfig = new ProducerConfig
                        {
                            BootstrapServers = producerSettings.BootstrapServers
                        };

                        var schemaRegistryConfig = new SchemaRegistryConfig
                        {
                            // Note: you can specify more than one schema registry url using the
                            // schema.registry.url property for redundancy (comma separated list). 
                            // The property name is not plural to follow the convention set by
                            // the Java implementation.
                            SchemaRegistryUrl = producerSettings.SchemaRegistryUrl,
                            // optional schema registry client properties:
                            SchemaRegistryRequestTimeoutMs = 5000,
                            SchemaRegistryMaxCachedSchemas = 10
                        };

                        var consumerConfig = new ConsumerConfig
                        {
                            BootstrapServers = producerSettings.BootstrapServers,
                            GroupId = "avro-specific-example-group"
                        };

                        var avroSerializerConfig = new AvroSerializerConfig
                        {
                            // optional Avro serializer properties:
                            BufferBytes = 100,
                            AutoRegisterSchemas = true
                        };

                        // Note: The User class in this project was generated using the Confluent fork of the avrogen.exe tool 
                        // (avaliable from: https://github.com/confluentinc/avro/tree/confluent-fork) which includes modifications
                        // that prevent namespace clashes with user namespaces that include the identifier 'Avro'. AvroSerializer
                        // and AvroDeserializer are also compatible with classes generated by the official avrogen.exe tool 
                        // (available from: https://github.com/apache/avro), with the above limitation.
                        
                        var schemaRegistry = new CachedSchemaRegistryClient(schemaRegistryConfig);

                        returnValue =
                            new ProducerBuilder<string, Entities.User>(producerConfig)
                                .SetKeySerializer(new AvroSerializer<string>(schemaRegistry))
                                .SetValueSerializer(new AvroSerializer<User>(schemaRegistry))
                                .Build();

                        _producers.Add(producerSettings, returnValue);
                    }
                }
            }

            return returnValue;
        }
    }
}
