// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.leonteq.horizonsat.avro.berntrade
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class BernTrade : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""BernTrade"",""namespace"":""com.leonteq.horizonsat.avro.berntrade"",""fields"":[{""name"":""tradeDate"",""type"":[""null"",{""type"":""int"",""logicalType"":""date""}]},{""name"":""time"",""type"":[""null"",{""type"":""int"",""logicalType"":""time-millis""}]},{""name"":""workOrderId"",""type"":[""null"",""string""]},{""name"":""isin"",""type"":[""null"",""string""]},{""name"":""localMnemonic"",""type"":[""null"",""string""]},{""name"":""securityShortName"",""type"":[""null"",""string""]},{""name"":""buySellIndicator"",""type"":[""null"",""string""]},{""name"":""currency"",""type"":[""null"",""string""]},{""name"":""tradeSize"",""type"":[""null"",""int""]},{""name"":""tradePrice"",""type"":[""null"",""double""]},{""name"":""settlementAmount"",""type"":[""null"",""double""]},{""name"":""fxRate"",""type"":[""null"",""double""]},{""name"":""settlementAmountCHF"",""type"":[""null"",""double""]},{""name"":""inputtingMemberId"",""type"":[""null"",""string""]},{""name"":""exchangeTradingCounterpartyMemberId"",""type"":[""null"",""string""]},{""name"":""tradeVersion"",""type"":[""null"",""int""]},{""name"":""transactionType"",""type"":[""null"",""string""]},{""name"":""tradingSegment"",""type"":[""null"",""string""]},{""name"":""transactionId"",""type"":[""null"",""string""]},{""name"":""eventTimestamp"",""type"":[""null"",{""type"":""long"",""logicalType"":""timestamp-millis""}]}]}");
		private System.Nullable<System.DateTime> _tradeDate;
		private System.Nullable<System.TimeSpan> _time;
		private string _workOrderId;
		private string _isin;
		private string _localMnemonic;
		private string _securityShortName;
		private string _buySellIndicator;
		private string _currency;
		private System.Nullable<System.Int32> _tradeSize;
		private System.Nullable<System.Double> _tradePrice;
		private System.Nullable<System.Double> _settlementAmount;
		private System.Nullable<System.Double> _fxRate;
		private System.Nullable<System.Double> _settlementAmountCHF;
		private string _inputtingMemberId;
		private string _exchangeTradingCounterpartyMemberId;
		private System.Nullable<System.Int32> _tradeVersion;
		private string _transactionType;
		private string _tradingSegment;
		private string _transactionId;
		private System.Nullable<System.DateTime> _eventTimestamp;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return BernTrade._SCHEMA;
			}
		}
		public System.Nullable<System.DateTime> tradeDate
		{
			get
			{
				return this._tradeDate;
			}
			set
			{
				this._tradeDate = value;
			}
		}
		public System.Nullable<System.TimeSpan> time
		{
			get
			{
				return this._time;
			}
			set
			{
				this._time = value;
			}
		}
		public string workOrderId
		{
			get
			{
				return this._workOrderId;
			}
			set
			{
				this._workOrderId = value;
			}
		}
		public string isin
		{
			get
			{
				return this._isin;
			}
			set
			{
				this._isin = value;
			}
		}
		public string localMnemonic
		{
			get
			{
				return this._localMnemonic;
			}
			set
			{
				this._localMnemonic = value;
			}
		}
		public string securityShortName
		{
			get
			{
				return this._securityShortName;
			}
			set
			{
				this._securityShortName = value;
			}
		}
		public string buySellIndicator
		{
			get
			{
				return this._buySellIndicator;
			}
			set
			{
				this._buySellIndicator = value;
			}
		}
		public string currency
		{
			get
			{
				return this._currency;
			}
			set
			{
				this._currency = value;
			}
		}
		public System.Nullable<System.Int32> tradeSize
		{
			get
			{
				return this._tradeSize;
			}
			set
			{
				this._tradeSize = value;
			}
		}
		public System.Nullable<System.Double> tradePrice
		{
			get
			{
				return this._tradePrice;
			}
			set
			{
				this._tradePrice = value;
			}
		}
		public System.Nullable<System.Double> settlementAmount
		{
			get
			{
				return this._settlementAmount;
			}
			set
			{
				this._settlementAmount = value;
			}
		}
		public System.Nullable<System.Double> fxRate
		{
			get
			{
				return this._fxRate;
			}
			set
			{
				this._fxRate = value;
			}
		}
		public System.Nullable<System.Double> settlementAmountCHF
		{
			get
			{
				return this._settlementAmountCHF;
			}
			set
			{
				this._settlementAmountCHF = value;
			}
		}
		public string inputtingMemberId
		{
			get
			{
				return this._inputtingMemberId;
			}
			set
			{
				this._inputtingMemberId = value;
			}
		}
		public string exchangeTradingCounterpartyMemberId
		{
			get
			{
				return this._exchangeTradingCounterpartyMemberId;
			}
			set
			{
				this._exchangeTradingCounterpartyMemberId = value;
			}
		}
		public System.Nullable<System.Int32> tradeVersion
		{
			get
			{
				return this._tradeVersion;
			}
			set
			{
				this._tradeVersion = value;
			}
		}
		public string transactionType
		{
			get
			{
				return this._transactionType;
			}
			set
			{
				this._transactionType = value;
			}
		}
		public string tradingSegment
		{
			get
			{
				return this._tradingSegment;
			}
			set
			{
				this._tradingSegment = value;
			}
		}
		public string transactionId
		{
			get
			{
				return this._transactionId;
			}
			set
			{
				this._transactionId = value;
			}
		}
		public System.Nullable<System.DateTime> eventTimestamp
		{
			get
			{
				return this._eventTimestamp;
			}
			set
			{
				this._eventTimestamp = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.tradeDate;
			case 1: return this.time;
			case 2: return this.workOrderId;
			case 3: return this.isin;
			case 4: return this.localMnemonic;
			case 5: return this.securityShortName;
			case 6: return this.buySellIndicator;
			case 7: return this.currency;
			case 8: return this.tradeSize;
			case 9: return this.tradePrice;
			case 10: return this.settlementAmount;
			case 11: return this.fxRate;
			case 12: return this.settlementAmountCHF;
			case 13: return this.inputtingMemberId;
			case 14: return this.exchangeTradingCounterpartyMemberId;
			case 15: return this.tradeVersion;
			case 16: return this.transactionType;
			case 17: return this.tradingSegment;
			case 18: return this.transactionId;
			case 19: return this.eventTimestamp;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.tradeDate = (System.Nullable<System.DateTime>)fieldValue; break;
			case 1: this.time = (System.Nullable<System.TimeSpan>)fieldValue; break;
			case 2: this.workOrderId = (System.String)fieldValue; break;
			case 3: this.isin = (System.String)fieldValue; break;
			case 4: this.localMnemonic = (System.String)fieldValue; break;
			case 5: this.securityShortName = (System.String)fieldValue; break;
			case 6: this.buySellIndicator = (System.String)fieldValue; break;
			case 7: this.currency = (System.String)fieldValue; break;
			case 8: this.tradeSize = (System.Nullable<System.Int32>)fieldValue; break;
			case 9: this.tradePrice = (System.Nullable<System.Double>)fieldValue; break;
			case 10: this.settlementAmount = (System.Nullable<System.Double>)fieldValue; break;
			case 11: this.fxRate = (System.Nullable<System.Double>)fieldValue; break;
			case 12: this.settlementAmountCHF = (System.Nullable<System.Double>)fieldValue; break;
			case 13: this.inputtingMemberId = (System.String)fieldValue; break;
			case 14: this.exchangeTradingCounterpartyMemberId = (System.String)fieldValue; break;
			case 15: this.tradeVersion = (System.Nullable<System.Int32>)fieldValue; break;
			case 16: this.transactionType = (System.String)fieldValue; break;
			case 17: this.tradingSegment = (System.String)fieldValue; break;
			case 18: this.transactionId = (System.String)fieldValue; break;
			case 19: this.eventTimestamp = (System.Nullable<System.DateTime>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
